### ISSUE TITLE
GUI: Run does not work when using Windows Console Host (legacy console)

### ISSUE THREAD

**Issue by przemoc** [NevermindNilas/TheAnimeScripter#33] opened 2024-06-19 19:53 UTC
Clicking Run starts `cmd.exe` window that fails immediately and closes afterward, so it's basically impossible to capture error message.

Copy-pasting command from Log and running it in Command Prompt (`cmd`) or PowerShell (`pwsh`) works, though.

---

OS: Windows 11 Pro 23H2 (22631.3737)
TAS: 1.8.6

**Comment by NevermindNilas** [comment] 2024-06-19 19:55
Testing rn.

**Comment by NevermindNilas** [comment] 2024-06-19 20:00
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/f1d2326e-ac30-40fd-b8fe-1917a5152a5d)

Weird, it works just fine for me

**Comment by NevermindNilas** [comment] 2024-06-19 20:04
Can you try running the script and sending the `log.txt` file here?

**Comment by przemoc** [comment] 2024-06-19 20:18
> It's worth noting if u hold onto the terminal ( basically grab it ) and don't let go of it, it will freeze it in place and it will never close unless you force close it yourself with task manager.

The issue is that when I grab it there is no content, so had to "unlock" it to continue and then content prints and window vanishes before I'm able to grab anything.

> Weird, it works just fine for me

Seeing your screenshot I suspect (but I may be wrong) that in your "Terminal settings" you have "Windows Terminal". Can you try with "Let Windows decide"?

![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/142372/6dbebabc-9f76-4611-b1cb-dbba3f5d57a4)

There are some command-line applications that work better that way, as Windows Terminal is extremely slow for some cases.

> Can you try running the script and sending the `log.txt` file here?

I managed to reproduce the issue by running it in `cmd.exe` outside of Windows Terminal.
`Win` + `R`, `cmd`, Enter 
and pasted the command there.

```
Microsoft Windows [Version 10.0.22631.3737]
(c) Microsoft Corporation. All rights reserved.

C:\Users\przemoc>C:\Tools\TAS\main.exe --input "c:/users/przemoc/videos/zoomit.mp4" --output "c:/users/przemoc/videos/zoomit-test.mp4" --resize_factor 1 --interpolate_factor 2 --upscale_factor 2 --interpolate_method rife4.17 --upscale_method shufflecugan --denoise_method dpir --dedup_method ssim --depth_method small --encode_method x264 --resize_method bilinear
Traceback (most recent call last):
  File "main.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\argumentsChecker.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\ytdlp.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "inquirer\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "inquirer\prompt.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "inquirer\themes.py", line 9, in <module>
  File "blessed\terminal.py", line 167, in __init__
  File "jinxed\win32.py", line 331, in get_term
  File "jinxed\win32.py", line 181, in set_console_mode
  File "jinxed\win32.py", line 86, in _check_bool
OSError: [WinError 87] The parameter is incorrect.
[8592] Failed to execute script 'main' due to unhandled exception!
```

**Comment by NevermindNilas** [comment] 2024-06-19 20:47
I went ahead and checked and it seems like I was on ` Let Windows Decide `.

Here's a test using manual commands and the suggested Win + R + CMD.
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/19a1f87b-af35-4394-b141-e1dc971f6e0c)

Here's a test using GUI and similar settings.
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/159346b8-dd4a-4cc1-9954-936c2a97aa32)

I fail to reproduce those errors though from a quick look at it, it seems like basically a few modules like Jinxed and Inquirer are not compatible with some part of the terminal. Weird...

I can't quite provide a fix for it unless you have the time necessary to try testing a few solutions I can come up with on the fly. 

One would be going [here](https://github.com/NevermindNilas/TheAnimeScripter/blob/main/src/uiLogic.py#L118) and replacing that function with
```py
        def runCommandInTerminal(command):
              os.system(["start", "cmd", "/c", f"{command} & exit"])
```

Ofc testing this would require either building TAS or having python 3.11 installed alongside the windows dependencies.

**Comment by przemoc** [comment] 2024-06-19 20:56
Your screenshot indicates you are running `cmd.exe` still in Windows Terminal.

I forgot there may be more to those settings, sorry for that. I changed it quite some time ago and used as such ever since.
In "Command Prompt" properties there is this legacy console option.

![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/142372/46a710a6-7a2c-4e29-9f68-52f87d57bfa5)

But to get there you would need to run `cmd.exe` w/o using Windows Terminal, and then RMB on title bar and choose properties. But to achieve that you would need to switch Terminal in settings to Windows Console Host first, because otherwise Windows will be starting it in Terminal.

**Comment by NevermindNilas** [comment] 2024-06-19 21:14
Oh I see, I went ahead and did what you've told me to and it seems like it is indeed running into issues.

I assume it's related to the colored prints and / or progress bar but it's just a hunch which uses some hackintoshy ascii stuff to work. After doing some googling I noticed that the [legacy console mode is no longer supported and it has been deprecated](https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features#:~:text=December%202023-,Legacy,-console%20mode) since December 2023 and nowadays W10 comes baked with `Windows Console Host` which does seem to work fine after a quick test and W11 defaults to `Microsoft Terminal`.

Sadly since this is such an edge case scenario and it would likely have to alter the code of TAS I can not provide a fix / support for it.

Sorry.

**Comment by przemoc** [comment] 2024-06-19 21:42
Sad to hear that. But I understand. VS Code also stopped supporting legacy consoles long time ago.

Maybe you could consider not hardcoding running via cmd, but through other way if user is on Win10 or newer?
Maybe calling Windows Terminal directly by using `wt` or something like that?
Not sure what's the best way, haven't researched it.

---

Short rant:
Microsoft replaces stuff with newer shiny things which are unfortunately often of lesser quality, and then calls old stuff no longer supported. Windows 11 has some nice things, but also a lot of broken stuff, like Alt+Tab view that can freeze and crash, which was unheard of in the past. Windows 7 is possibly the last one where some QA still existed. I skipped 8/8.1/10 (just like I skipped Vista before), but couldn't skip 11...

**Comment by NevermindNilas** [comment] 2024-06-19 21:49
I wasn't aware of the existence of `wt`, interesting, Matter of fact I didn't even try running with a different terminal option since I knew that cmd.exe just work so there was no point in trying anything else.

I will look into it but I won't make any false promises.

============
Very short rant;

Why do I need to install 3 different softwares that each use ram and need to modify my registry, quite possibly risking bricking my system ( U never know ) to just change how my taskbar looks whereas Linux has this feature built in???

**Comment by NevermindNilas** [comment] 2024-06-19 22:13
Since this issue is no longer relevant I will close it and if by any chance I will want to fix it in the future ( or someone else will want to ) I will go ahead and open it again. Thank you!

**Closed by NevermindNilas** 2024-06-19 22:13 UTC
Labels: wontfix

**Comment by przemoc** [comment] 2024-06-19 22:15
Sure. Are you ok with me creating separate issue for using alternative means to start command?

**Comment by NevermindNilas** [comment] 2024-06-19 22:16
Sounds good to me but I will emphasise the fact that I can't promise any fix for it and it will likely be a dormant issue.
