### ISSUE TITLE
Can't set pix_fmt

### ISSUE THREAD

**Issue by Ewillian9** [NevermindNilas/TheAnimeScripter#16] opened 2024-03-23 02:43 UTC
Hi,
not sure if i'm doing something wrong here. My source is 10 bits, and i wanted to output 10 bit too.
[log.txt](https://github.com/NevermindNilas/TheAnimeScripter/files/14729988/log.txt)

I tried to put the -pix_fmt yuv420p10le before, in the middle or at the end but always the same. (even tried yuv420p which is the default but same issue)

Anyway, many thanks for your hard work

**Comment by NevermindNilas** [comment] 2024-03-23 02:52
Hi,

Thanks for trying out the script.
Currently, as per the notice in the [Parameters Guide](https://github.com/NevermindNilas/TheAnimeScripter/blob/main/PARAMETERS.MD#encoding-settings) ( see custom encoder ), 

`-pix_fmt` is currently hardcoded due to the fact that Depth Maps and Segmentation ( Rotobrush ) need certain formats for the encoding to work as intended.

The relevant code can be found [here](https://github.com/NevermindNilas/TheAnimeScripter/blob/main/src/ffmpegSettings.py#L360)

That's a limitation which I couldn't figure out just yet.

**Comment by NevermindNilas** [comment] 2024-03-23 02:58
Interesting sidenote,

```py
              if "-pix_fmt" in custom_encoder_list:
                    raise ValueError(
                        "The '-pix_fmt' option is hardcoded in the script and should not be included in the custom encoder settings."
                    )
```

I normally have a call in the log.txt that should alert users that `-pix_fmt` is hardcoded but it seems like your log.txt doesn't mention it. Well I guess we will strike 2 birds with one stone.

**Comment by NevermindNilas** [comment] 2024-03-23 03:53
Should be fixed with:
https://github.com/NevermindNilas/TheAnimeScripter/commit/b207355e09978951879df2c132cfc2b22c8c1aca

Thank you for the report, feel free to open more issues if you find any.

**Closed by NevermindNilas** 2024-03-23 03:53 UTC

**Comment by Ewillian9** [comment] 2024-03-23 12:28
Wow thanks, you were so fast. Got it. I'll try to build it myself from lastest.

Have a good day
